export class Const {
  static LEFT_DIRECTION = 1
  static RIGHT_DIRECTION = 2
  static UP_DIRECTION = 3
  static DOWN_DIRECTION = 4

  static TILE_SIZE = 50

  static UPGRADE_MAX_LEVEL = 5

  static CANVAS_WIDTH = 800
  static CANVAS_HEIGHT = 580
  static HUD_HEIGHT = 84
  static KEY_1 = 49
  static KEY_2 = 50
  static KEY_3 = 51

  static TOWER_OFFSET = 5

  static ALPHA_INFLUENCE_AREA_FILL = 50
  static ALPHA_INFLUENCE_AREA_STROKE = 120

  static EXPLOSION_OFFSET = 25

  static GAME_STATUS_PLAYING = 0
  static GAME_STATUS_GAME_OVER = 1

  static WAVE_PROGRESS_DELAY = 35
  static BOSS_PROGRESS_DELAY = Const.WAVE_PROGRESS_DELAY * 6

  static MONEY_MULTIPLICATOR = 10

  static ID_LEVEL_VALID_FOR_UNIT_TESTING = 1
  static ID_LEVEL_INVALID_FOR_UNIT_TESTING = 6666
  static ID_LEVEL_INVALID_WITHOUT_ROWSMAP_FOR_UNIT_TESTING = 6667

  static DELAY_UPGRADE_MULTIPLIER = 5

  static MAGIC_STATUS_ALIVE = 0
  static MAGIC_STATUS_DEAD = 1
}
